# Generated by Django 6.0.2 on 2026-02-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_voter_vote_user_remove_vote_vote_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('DUPLICATE', 'Duplicate Vote'), ('BURST', 'Burst Voting')], max_length=20)),
                ('severity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
