# Generated by Django 6.0.2 on 2026-02-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_anomalylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
