# Generated by Django 6.0.2 on 2026-03-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_suspicious'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
